server:
  port: 8081

spring:
  application:
    name: fraud
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
      username: rootuser
      password: rootpass
      authentication-database: admin
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true